# -*- coding: utf-8 -*-
"""Custom_env_best_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMEIoYyqEbT5kQZW-6XLArnbyKTOxPx0
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pip install highway-env
# %pip install stable-baselines3
# %pip install optuna

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/cs-272-final-project/custom/best-model

# Ignore warnings
import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning,)
warnings.filterwarnings("ignore", message=".*Kernel._parent_header.*")

# optuna_ppo_highway.py
import os, glob, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import optuna
from optuna.exceptions import TrialPruned
import gymnasium as gym
from custom_env import AccidentEnv
import highway_env  # registers env ids
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

try:
    gym.register(id="MyCustomEnv-v0", entry_point="custom_env:AccidentEnv")
except gym.error.RegistrationError:
    print("Env already registered")
    pass  # already registered (e.g., on reruns)
except Exception as e:
    print(e)

# ------------------------------ Config ------------------------------
SEED = 42
ENV_ID = "MyCustomEnv-v0"


# Folder layout (run this from highway/hyperparam-tuned or any folder you want)
BASE_DIR     = os.getcwd()
RUNS_ROOT    = os.path.join(BASE_DIR, "runs_monitor")     # per-trial monitor logs
FINAL_ROOT   = os.path.join(RUNS_ROOT, "final_best")      # final training logs
MODELS_DIR   = os.path.join(BASE_DIR, "models")
PLOTS_DIR    = os.path.join(BASE_DIR, "plots")
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(PLOTS_DIR, exist_ok=True)

# ------------------------------ Helpers ------------------------------

def make_train_env(monitor_dir, n_envs=4):
    os.makedirs(monitor_dir, exist_ok=True)
    return make_vec_env(
        ENV_ID,
        n_envs=n_envs,
        seed=SEED,
        monitor_dir=monitor_dir,   # logs training episodes to CSVs
    )

# --- Plot 1: learning curve from Monitor CSVs (episodes on X) ---
def plot_learning_curve_monitor(monitor_dir: str, out_png: str, smooth_window: int = 50, title="Learning Curve — Custom Env PPO (tuned)"):
    files = sorted(glob.glob(os.path.join(monitor_dir, "**", "*.csv"), recursive=True))
    if not files:
        raise FileNotFoundError(f"No monitor CSVs under: {monitor_dir}")

    dfs = []
    for f in files:
        try:
            df = pd.read_csv(f, comment="#")
            if "r" in df.columns:
                dfs.append(df[["r"]].copy())
        except Exception:
            pass
    if not dfs:
        raise RuntimeError("Found CSVs but no episodic returns (column 'r')")

    log = pd.concat(dfs, ignore_index=True)
    log["episode"] = np.arange(1, len(log) + 1)
    win = max(1, min(smooth_window, len(log)))
    log["r_smooth"] = log["r"].rolling(win, min_periods=1).mean()

    os.makedirs(os.path.dirname(out_png) or ".", exist_ok=True)
    plt.figure()
    plt.plot(log["episode"], log["r_smooth"])
    plt.xlabel("Training Episodes")
    plt.ylabel("Mean Episodic Return (smoothed)")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_png, dpi=140)
    plt.close()
    print(f"[plot] saved: {out_png}")

# --- Plot 2: 500-episode deterministic evaluation violin ---
def evaluate_and_plot_violin(model_path: str, out_png: str,
                             env_id: str = ENV_ID,
                             n_episodes: int = 500,
                             deterministic: bool = True,
                             seed: int = SEED):
    env = gym.make(env_id)
    model = PPO.load(model_path)

    returns = []
    for _ in range(n_episodes):
        obs, info = env.reset(seed=seed)
        done = False
        ep_ret = 0.0
        while not done:
            action, _ = model.predict(obs, deterministic=deterministic)  # no exploration
            obs, reward, terminated, truncated, info = env.step(action)
            ep_ret += reward
            done = terminated or truncated
        returns.append(ep_ret)
    env.close()

    os.makedirs(os.path.dirname(out_png) or ".", exist_ok=True)
    plt.figure()
    plt.violinplot([returns], showmeans=True)
    plt.xticks([1], ["PPO"])
    plt.ylabel(f"Episodic Return (n={n_episodes}, deterministic)")
    plt.title("Performance Test — Custom Env PPO (tuned)")
    plt.tight_layout()
    plt.savefig(out_png, dpi=140)
    plt.close()
    print(f"[plot] saved: {out_png}")

# --- Metric from Monitor CSVs: mean of last-K episode returns ---
def last_k_mean(monitor_dir: str, k: int = 200) -> float:
    files = sorted(glob.glob(os.path.join(monitor_dir, "**", "*.csv"), recursive=True))
    vals = []
    for f in files:
        try:
            df = pd.read_csv(f, comment="#")
            if "r" in df.columns:
                vals.extend(df["r"].tolist())
        except Exception:
            pass
    if not vals:
        return -1e9
    vals = vals[-k:] if len(vals) >= k else vals
    return float(np.mean(vals))

# ------------------------------ Optuna objective ------------------------------
def objective(trial: optuna.trial.Trial) -> float:
    # Search space (solid defaults for PPO)
    lr         = trial.suggest_float("lr", 1e-5, 3e-3, log=True)
    n_steps    = trial.suggest_categorical("n_steps", [1024, 2048])
    batch_size = trial.suggest_categorical("batch_size", [64, 128, 256])
    clip       = trial.suggest_float("clip_range", 0.1, 0.3)
    gae_lam    = trial.suggest_float("gae_lambda", 0.90, 0.98)
    gamma      = trial.suggest_float("gamma", 0.97, 0.999)
    ent_coef   = trial.suggest_float("ent_coef", 1e-4, 1e-2, log=True)
    n_epochs   = trial.suggest_categorical("n_epochs", [5, 10])

    trial_dir = os.path.join(RUNS_ROOT, f"trial_{trial.number:03d}")
    env = make_train_env(trial_dir, n_envs=4)

    model = PPO(
        "MlpPolicy",
        env,
        verbose=0,
        seed=SEED,
        learning_rate=lr,
        n_steps=n_steps,
        batch_size=batch_size,
        clip_range=clip,
        gae_lambda=gae_lam,
        gamma=gamma,
        ent_coef=ent_coef,
        n_epochs=n_epochs,
    )

    # ---- run fixed number of PPO updates; prune early if underperforming ----
    n_updates = 8                                # small, fast trials
    steps_per_update = n_steps * 4               # n_envs = 4
    for u in range(n_updates):
        model.learn(total_timesteps=steps_per_update,
                    reset_num_timesteps=False, progress_bar=False)

        if u >= 3:  # warmup a few updates before judging
            score = last_k_mean(trial_dir, k=100)
            trial.report(score, step=u)
            if trial.should_prune():
                env.close()
                raise TrialPruned()

    env.close()

    # Score = mean last-K ep returns from Monitor CSVs
    return last_k_mean(trial_dir, k=200)

def main():
    os.makedirs(RUNS_ROOT, exist_ok=True)

    # 1) Hyperparameter search
    sampler = optuna.samplers.TPESampler(seed=SEED, n_startup_trials=5)
    pruner  = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)

    study = optuna.create_study(direction="maximize", sampler=sampler, pruner=pruner)
    study.optimize(objective, n_trials=16, timeout=7*60*60)

    print("Best trial:", study.best_trial.number)
    print("Best value (last-k mean):", study.best_value)
    print("Best params:", study.best_params)

    with open(os.path.join(MODELS_DIR, "ppo_best_params_custom.json"), "w") as f:
        json.dump(study.best_params, f, indent=2)

    # 2) Final training with best params (longer budget)
    os.makedirs(FINAL_ROOT, exist_ok=True)
    env = make_train_env(FINAL_ROOT, n_envs=4)

    bp = study.best_params
    model = PPO(
        "MlpPolicy",
        env,
        verbose=1,
        seed=SEED,
        learning_rate=bp["lr"],
        n_steps=bp["n_steps"],
        batch_size=bp["batch_size"],
        clip_range=bp["clip_range"],
        gae_lambda=bp["gae_lambda"],
        gamma=bp["gamma"],
        ent_coef=bp["ent_coef"],
        n_epochs=bp["n_epochs"],
    )

    total_timesteps = bp["n_steps"] * 4 * 40  # ~40 updates
    model.learn(total_timesteps=total_timesteps, progress_bar=False)
    env.close()

    final_model_path = os.path.join(MODELS_DIR, "ppo_custom_env_tuned")
    model.save(final_model_path)
    print(f"[model] saved: {final_model_path}.zip")

    # 3) Plots
    plot_learning_curve_monitor(
        FINAL_ROOT,
        os.path.join(PLOTS_DIR, "learning_custom_env_tuned.png"),
    )

    evaluate_and_plot_violin(
        final_model_path + ".zip",
        os.path.join(PLOTS_DIR, "violin_custom_env_tuned.png"),
        env_id=ENV_ID,
        n_episodes=500,
        deterministic=True,
    )

if __name__ == "__main__":
    main()